version: "3.9"

services:
  sql-runner:
    container_name: sql-runner
    mem_limit: 2g
    mem_reservation: 2g
    build: 
      context: ./sql-runner
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - DB_USER=will_be_provided_by_release
      - DB_PASS=will_be_provided_by_release
      - DB_HOST=will_be_provided_by_release

  database:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
