version: "3.9"

services:
  sql-runner:
    container_name: sql-runner
    mem_limit: 2g
    mem_reservation: 2g
    build: 
      context: ./sql-runner
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${MSSQL_DEMO_RDS_DB_POOL_HOST:-database}
      - DB_USER=${MSSQL_DEMO_RDS_DB_POOL_HOST:-sa}
      - DB_PASS=${MSSQL_DEMO_RDS_DB_POOL_HOST:-Pass@word}

# In addition to the ephemeral Amazon RDS MSSQL database we will use
# via Release Instance Datasets, we will also include an ephemeral
# containerized version of MSSQL. Either option is valid with Release: 
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
